### ISSUE TITLE
Not compatible with latest Google VR SDK

### ISSUE THREAD

**Issue by itsfenix** [googlevr/daydream-elements#2]
Hi guys. Stellar work with Elements.

Problem: Unity imports daydream-elements package with compilation errors from GVR code if the GVR version is > 1.5.0.

My Workaround: Use GVR 1.5.0 for now until an update is released

Any idea when the update might take place?
Thanks!

**Comment by dsternfeld7** [comment]
Thank you!

An update to GVR 1.7.0 is forthcoming in the near future. I can't give an exact date, but it will be soon!

Thanks,

Dan

**Comment by itsfenix** [comment]
Thanks for the update. good luck with that

**Comment by dsternfeld7** [comment]
The update has been released.
