### ISSUE TITLE
Not compatible with Google VR SDK 1.100.x

### ISSUE THREAD

**Issue by tazzkiller** [googlevr/daydream-elements#3]
ArmModel scripts return error on unity.

**Comment by dsternfeld7** [comment]
Thanks for the report. Daydream Elements will be updated to use the 1.100.1 soon.

-Dan

**Comment by starantino** [comment]
Yep, same issue here.

**Comment by dsternfeld7** [comment]
The update for GVR SDK 1.100.1 is now live.

Thanks!
