### ISSUE TITLE
Failure to import

### ISSUE THREAD

**Issue by HeyBishop** [googlevr/daydream-elements#4]
I'm getting the following error when importing the Unity Package:

![daydreamimporterror](https://user-images.githubusercontent.com/29380115/32035332-77e797e8-b9e6-11e7-989a-cf268ebb3533.jpg)

**Comment by HeyBishop** [comment]
I just realized, more information might be appreciated:

Windows 10
Unity 2017.2.0f3
GVR SDK for Unity v1.100.1

Would any more information be of value?

**Comment by fredsa** [comment]
Looks like the import is attempting to overwrite an existing file which is open / in use.

To fix this, try:
1. Close Unity
1. Open Unity, but don't hit "Play"
1. Retry the import

A more robust solution:
1. Close Unity
1. Delete the Assets/GoogleVR/Plugins folder (put the contents somewhere safe)
1. Open Unity, ignore any errors related to missing libraries
1. Retry the import

**Comment by HeyBishop** [comment]
The more robust solution got me further along, but now I have thousands of errors, such as this one:

TypeLoadException: Could not load type 'UnityEditor.Tools' from assembly 'UnityEditor, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
UnityEditor.SceneView.OnGUI () (at C:/buildslave/unity/build/Editor/Mono/SceneView/SceneView.cs:1513)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:285)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:278)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:245)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by fredsa** [comment]
Sounds like your project has gotten into a bad state, unrelated to Google VR.

General process for getting back to a working state is:
1. Close Unity
2. Delete temp files, especially `/Temp/` and `/Library/` folders.
3. Restart Unity

If that doesn't help, make sure that your environment doesn't have other issues:
1. Create a brand new Unity project
2. Import the Google VR SDK into this new project

Assuming that all works fine, you can copy over Unity assets and script from your "broken" project into this working project.
