### ISSUE TITLE
Scripts could be better organized/put into namespaces

### ISSUE THREAD

**Issue by thesambassador** [googlevr/daydream-elements#5]
I was trying to use some of the Daydream Elements in a project, and I have my own Object Pool implementation called "ObjectPoolManager".  Daydream Elements also seems to include a same-named script for one of its demos.  I tried deleting the "Demos" folder since I didn't need the demos, but then a number of other scripts in other folders broke as well.  This means I have to go through and either delete all the unnecessary references (not being sure if I'm deleting things that I might want to use from Elements in the future), or ignore it and namespace my own implementation (with also the added risk of potentially accidentally using the Daydream version if I forget a using statement.

Overall, scripts that are used in multiple demos should probably not be in the "Demos" folder at all, and scripts outside of the "Demos" folder should not have dependencies in the "Demos" folder.

**Comment by dsternfeld7** [comment]
Thanks for the feedback!

The scripts you are referring to are actually part of the [GVR SDK for Unity](https://github.com/googlevr/gvr-unity-sdk) included with Daydream Elements, not Daydream Elements itself (which is already namespaced). Anything inside of the DaydreamElements folder that isn't within a demo folder shouldn't have any dependencies on files within DaydreamElements/*/demo/* folders. If you notice an instance where this isn't the case, please let us know.

By chance, the code that you are referring to is actually being migrated from the GVR SDK for Unity into Daydream Elements. In the next release, the code will be namespaced and live within the folder DaydreamElements/Common.

In the meantime...

The only folder that has dependencies on the folder you deleted is DaydreamElements/Main which is primarily the UI for navigating between elements. You can safely delete Main and still use any of the individual elements just fine.

Thanks,

Dan

**Comment by dsternfeld7** [comment]
Resolve in Release 1.12.
